
#
# TODO add description and disclaimer
#

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.ssh.insert_key = false


    (1..2).each do |id|
        re_name  = ( "vqfx" + id.to_s ).to_sym
        pfe_name = ( "vqfx" + id.to_s + "-pfe" ).to_sym

        ##############################
        ## Packet Forwarding Engine ##
        ##############################
        config.vm.define pfe_name do |vqfxpfe|
            vqfxpfe.vm.hostname = "vqfx#{id}-pfe"
            vqfxpfe.vm.box = 'vqfx10k-pfe'

            # DO NOT REMOVE / NO VMtools installed
            vqfxpfe.vm.synced_folder '.', '/vagrant', disabled: true

            vqfxpfe.vm.network 'private_network', auto_config: false, nic_type: '82540EM', virtualbox__intnet: "vqfx_internal_#{id}"

            vqfxpfe.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--memory", "2048"]
            end
        end

        ##########################
        ## Routing Engine  #######
        ##########################
        config.vm.define re_name do |vqfx|
            vqfx.vm.hostname = "vqfx#{id}"
            vqfx.vm.box = 'vqfx10k-re'

            # DO NOT REMOVE / NO VMtools installed
            vqfx.vm.synced_folder '.', '/vagrant', disabled: true

            # Management port
            vqfx.vm.network 'private_network', auto_config: false, nic_type: '82540EM', virtualbox__intnet: "vqfx_internal_#{id}"
            vqfx.vm.network 'private_network', auto_config: false, nic_type: '82540EM', virtualbox__intnet: "reserved-bridge"

            # Dataplane ports
            (1..6).each do |seg_id|
               vqfx.vm.network 'private_network', auto_config: false, nic_type: '82540EM', virtualbox__intnet: "seg#{seg_id}"
            end

            vqfx.vm.provider "virtualbox" do |v|
              v.customize ["modifyvm", :id, "--memory", "1024"]
            end

            config.vm.provision "ansible" do |ansible|
                ansible.groups = {
                    "vqfx10k" => ["vqfx1", "vqfx2" ],
                    "vqfx10k-pfe"  => ["vqfx1-pfe", "vqfx2-pfe"],
                    "all:children" => ["vqfx10k", "vqfx10k-pfe"]
                }
                ansible.playbook = "provisioning/save-config.p.yaml"
            end
        end
    end
end
