# This task gets all Junos configuration from all devices
- name: Get configuration
  hosts: vqfx10k
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Getting config ... please wait
      juniper_junos_config:
        retrieve: commited
        host: "{{ ansible_ssh_host }}"
        port: "{{ ansible_ssh_port|string }}"
        user: root
        passwd: Juniper
        format: text
        dest: "{{ inventory_hostname }}.conf"
        logfile: /tmp/changes.log
