
#
# TODO add description and disclaimer
#

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|



        re_name  = "vqfx"
        pfe_name = "vqfx-pfe"

        ##############################
        ## Packet Forwarding Engine ##
        ##############################
        config.vm.define pfe_name do |vqfxpfe|
            vqfxpfe.ssh.insert_key = false
            vqfxpfe.vm.hostname = "vqfx-pfe"
            vqfxpfe.vm.box = 'vqfx10k-pfe'

            # DO NOT REMOVE / NO VMtools installed
            vqfxpfe.vm.synced_folder '.', '/vagrant', disabled: true

            vqfxpfe.vm.network 'private_network', auto_config: false, nic_type: '82540EM', virtualbox__intnet: "vqfx_internal"

            vqfxpfe.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--memory", "1000"]
            end
        end

        ##########################
        ## Routing Engine  #######
        ##########################
        config.vm.define re_name do |vqfx|
            vqfx.vm.hostname = "vqfx"
            vqfx.vm.box = 'vqfx10k-re'
            vqfx.ssh.insert_key = false
            # DO NOT REMOVE / NO VMtools installed
            vqfx.vm.synced_folder '.', '/vagrant', disabled: true

            # Management port
            vqfx.vm.network 'private_network', auto_config: false, nic_type: '82540EM', virtualbox__intnet: "vqfx_internal"
            vqfx.vm.network 'private_network', auto_config: false, nic_type: '82540EM', virtualbox__intnet: "reserved-bridge"

              vqfx.vm.network 'private_network', ip: "10.1.2.1", nic_type: '82540EM', virtualbox__intnet: '1-2'
            ## Dataplane ports
            #(1..6).each do |seg_id|
            #    vqfx.vm.network 'private_network', auto_config: false, nic_type: 'virtio', virtualbox__intnet: "seg#{seg_id}"
            #end

            vqfx.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--memory", "1024"]
            end
        end

        ##########################
        ## Server  #######
        ##########################
        config.vm.define "server" do |srv|
            srv.vm.box = "robwc/minitrusty64"
            srv.vm.hostname = "server"
            srv.vm.network 'private_network', auto_config: false, virtualbox__intnet: '1-2'
            srv.ssh.insert_key = true
        end
end
